parameters:
    itr_response_builder.response_builder_factory.class: Itr\ResponseBuilderBundle\ResponseBuilder\ResponseBuilderFactory

services:
    itr_response_builder.response_builder_factory:
        class: %itr_response_builder.response_builder_factory.class%
        arguments: [%itr_response_builder.default_format%]

    response_builder_factory:
        alias: itr_response_builder.response_builder_factory